[package]

description = "A usable Cassandra CQL driver (this replaces the previous cql-ffi package).\nWraps the DataStax c++ native driver and uses cql-bindgen vian rust-bindgen.\nWorks with both stable and nightly"
license = "Apache-2.0"
homepage = "https://github.com/tupshin/cassandra-rust"
repository = "https://github.com/tupshin/cassandra-rust"
name = "cassandra"
version = "0.3.0"
authors = ["Tupshin Harper <tupshin@tupshin.com>"]



[lib]
name = "cassandra"

[dependencies]
cql_bindgen = "*"
libc = "*"
num = "*"

[[bin]]
name="async"
path="src/examples/async.rs"

[[bin]]
name="basic"
path="src/examples/basic.rs"

[[bin]]
name="batch"
path="src/examples/batch.rs"

[[bin]]
name="bind_by_name"
path="src/examples/bind_by_name.rs"

[[bin]]
name="collections"
path="src/examples/collections.rs"

# [[bin]]
# name="logging"
# path="src/examples/logging.rs"

[[bin]]
name="maps"
path="src/examples/maps.rs"

[[bin]]
name="paging"
path="src/examples/paging.rs"

[[bin]]
name="prepared"
path="src/examples/prepared.rs"

[[bin]]
name="schema_meta"
path="src/examples/schema_meta.rs"

[[bin]]
name="simple"
path="src/examples/simple.rs"

[[bin]]
name="uuids"
path="src/examples/uuids.rs"
