[package]

description = "An unsafe wrapper of the DataStax C++ CQL driver"
license = "Apache-2.0"
homepage = "https://github.com/tupshin/cql-ffi"
repository = "https://github.com/tupshin/cql-ffi"
name = "cql_ffi"
version = "0.0.8"
authors = ["Tupshin Harper <tupshin@tupshin.com>"]



[lib]
name = "cql_ffi"

[dependencies]
cql_bindgen = "0.0.1"

[[bin]]
name="async"
path="src/examples/async.rs"

[[bin]]
name="basic"
path="src/examples/basic.rs"

[[bin]]
name="batch"
path="src/examples/batch.rs"

[[bin]]
name="bind_by_name"
path="src/examples/bind_by_name.rs"
